#!/bin/bash

layout_poetry() {
  if [[ ! -f pyproject.toml ]]; then
    log_error 'No pyproject.toml found.  Use `poetry new` or `poetry init` to create one first.'
    exit 2
  fi

  if [[ ! -d .venv ]]; then
      poetry install
  fi
  local VENV=$(poetry env list --full-path | cut -d' ' -f1)
  VENV=${VENV}/bin
  export VIRTUAL_ENV=$(echo "${VENV}" | rev | cut -d'/' -f2- | rev)
  export POETRY_ACTIVE=1
  PATH_add "${VENV}"
}

layout_poetry